name: Deploy Spring Boot App

on:
  push:
    branches:
      - develop  # Cambia esto si tu rama principal es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Check out code
        uses: actions/checkout@v2

      # Paso 2: Configurar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Especifica la versión de Java que necesitas

      # Paso 3: Construir la aplicación con Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Paso 4: Construir y publicar la imagen Docker
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false  # Cambia a true si deseas subir la imagen
          tags: your-docker-image-name
          distribution: your-distribution-value  # Proporciona aquí el valor requerido
          
      # Paso 5: Ejecutar el contenedor Docker
      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 your-docker-image-name  # Reemplaza con el nombre de tu imagen
