# .github/workflows/deploy.yml

name: Deploy Spring Boot App

on:
  push:
    branches:
      - develop # Cambia esto si tu rama principal es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t your-docker-image-name .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 your-docker-image-name
